/**
 * Builds the OpenAPI descriptions forgewright is generated from.
 *
 * For each forge in spec/<forge>/config.json:
 *   1. download the pinned upstream description
 *   2. apply spec/<forge>/overlays/*.yaml, in order (OpenAPI Overlay)
 *   3. keep only the operations listed in config.json, then prune unused components
 *   4. write spec/<forge>/openapi.json (used to validate fixtures)
 *   5. write src/services/<forge>/openapi.ts (used by the typed client)
 *
 * Fails if an overlay action matches nothing or a listed operation is missing,
 * so upstream fixes and regressions surface here instead of at runtime.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { openapiFilter, openapiOverlay, parseFile } from 'openapi-format';
import openapiTS, { astToString } from 'openapi-typescript';

const FORGES = ['github', 'gitlab'];
const METHODS = ['get', 'put', 'post', 'delete', 'patch', 'head', 'options'];

type Doc = Record<string, unknown>;
type PathItem = Record<string, unknown>;

interface Config {
  source: string;
  operations: string[];
}

async function applyOverlays(doc: Doc, dir: string): Promise<Doc> {
  let files: string[] = [];
  try {
    files = (await readdir(dir)).filter((f) => /\.ya?ml$/.test(f)).sort();
  } catch {
    return doc;
  }

  for (const file of files) {
    const overlaySet = await parseFile(join(dir, file));
    const { data, resultData } = await openapiOverlay(doc, { overlaySet });
    if (resultData.totalUnusedActions) {
      throw new Error(
        `${file}: ${resultData.totalUnusedActions} action(s) matched nothing. ` +
          'Upstream may have fixed or moved the target.',
      );
    }
    console.log(`  applied ${file}`);
    doc = data;
  }
  return doc;
}

/**
 * Keeps only the listed operations. Custom on purpose: openapi-format's
 * `inverseOperationIds` filter also deletes schema properties named after
 * HTTP methods (e.g. `head` in GitHub's create-pull-request body), as of
 * openapi-format 1.33.7.
 */
function keepOperations(doc: Doc, operations: string[]): Doc {
  const wanted = new Map<string, Set<string>>();
  for (const op of operations) {
    const [method, path] = op.split(' ');
    const methods = wanted.get(path) ?? new Set();
    methods.add(method.toLowerCase());
    wanted.set(path, methods);
  }

  const paths = doc.paths as Record<string, PathItem>;
  const kept: Record<string, PathItem> = {};
  for (const [path, methods] of wanted) {
    const item = paths[path];
    const next: PathItem = {};
    for (const [key, value] of Object.entries(item ?? {})) {
      if (!METHODS.includes(key) || methods.has(key)) next[key] = value;
    }
    for (const method of methods) {
      if (!next[method]) {
        throw new Error(
          `Operation not in description: ${method.toUpperCase()} ${path}`,
        );
      }
    }
    kept[path] = next;
  }

  return { ...doc, paths: kept, webhooks: undefined, 'x-webhooks': undefined };
}

async function build(forge: string) {
  console.log(`${forge}:`);
  const specDir = join('spec', forge);
  const config = JSON.parse(
    await readFile(join(specDir, 'config.json'), 'utf8'),
  ) as Config;

  let doc = await parseFile(config.source);
  doc = await applyOverlays(doc, join(specDir, 'overlays'));
  doc = keepOperations(doc, config.operations);
  doc = (
    await openapiFilter(doc, {
      filterSet: {
        unusedComponents: [
          'schemas',
          'parameters',
          'responses',
          'requestBodies',
          'headers',
          'examples',
        ],
      },
    })
  ).data;

  await writeFile(
    join(specDir, 'openapi.json'),
    JSON.stringify(doc, null, 2) + '\n',
  );

  const header = [
    '/**',
    ` * Generated by scripts/update-specs.ts from ${config.source}`,
    ' * Do not edit by hand. Run `npm run specs:update`.',
    ' */',
    '',
  ].join('\n');
  const ast = await openapiTS(doc as never);
  await writeFile(
    join('src', 'services', forge, 'openapi.ts'),
    header + astToString(ast),
  );
  console.log(`  ${config.operations.length} operations`);
}

for (const forge of process.argv.slice(2).length
  ? process.argv.slice(2)
  : FORGES) {
  await build(forge);
}
